// ---------------------------------------------------------------------------------------------------------------------
// Copyright 2025 Navtech Radar Limited
// This file is part of IASDK which is released under The MIT License (MIT).
// See file LICENSE.txt in project root or go to https://opensource.org/licenses/MIT
// for full license details.
//
// Disclaimer:
// Navtech Radar is furnishing this item "as is". Navtech Radar does not provide 
// any warranty of the item whatsoever, whether express, implied, or statutory,
// including, but not limited to, any warranty of merchantability or fitness
// for a particular purpose or any warranty that the contents of the item will
// be error-free.
// In no respect shall Navtech Radar incur any liability for any damages, including,
// but limited to, direct, indirect, special, or consequential damages arising
// out of, resulting from, or any way connected to the use of the item, whether
// or not based upon warranty, contract, tort, or otherwise; whether or not
// injury was sustained by persons or property or otherwise; and whether or not
// loss was sustained from, or arose out of, the results of, the item, or any
// services that may be provided by Navtech Radar.
// ---------------------------------------------------------------------------------------------------------------------
#ifndef MONOTONIC_OBSERVATION_H
#define MONOTONIC_OBSERVATION_H

#include "Time_core.h"

namespace Navtech::Time                         { class Duration; }
namespace Navtech::Time::Real_time              { class Observation; }
namespace Navtech::Time::Thread_safe            { class Duration; }
namespace Navtech::Time::Thread_safe::Monotonic { class Observation; }

namespace Navtech::Time::Monotonic {

    // --------------------------------------------------------------------------------
    // An Observation represents a point in time; more specifically, it represents a 
    // duration since the start of the Clock’s epoch.  An Observation is used to 
    // mark/record an event occurrence.
    // Observations are usually generated by the Clock (via the now() function); but may 
    // be computed from other Observations using Durations as offsets.
    // Since Monotonic::Clocks do not align with a real-time (wall) clock there is no 
    // interface for extracting the day/date/month/etc. from a Monotonic::Observation.
    //
    // Observations support some operator overloads, as follows:
    // - Observations may be compared for equality/inequality.  Equality indicates that 
    //   both Observations mark the same moment in time.
    // - Greater-than indicates that one Observation is later the other; less-than indicates 
    //   that one Observation is earlier than the other.
    // - Adding two Observations has no meaning.
    // - A Duration may be added to, or subtracted from, an Observation.  The result is 
    //   a new Observation.
    // - Subtracting two Observations yields the Duration between them.  
    // - If a later Observation (t1) is subtracted from an earlier Observation (t0) the 
    //   result will yield a negative Duration.  That is, t0 – t1 => -d. 
    //
    class Observation : public Observation_tag {
    public:
        Observation() = default;
        explicit Observation(const Duration& init);
        
        Duration since_epoch()  const;
        Real_time::Observation to_real_time() const;

        timespec to_timespec() const;

        Observation& operator+=(const Duration& rhs);
        Observation& operator-=(const Duration& rhs);

    protected:
        std::chrono::time_point<std::chrono::steady_clock, std::chrono::microseconds> time { };
    };

    // Non-member API
    //
    Duration abs_diff(const Observation& lhs, const Observation& rhs);


    // --------------------------------------------------------------------------------
    // Monotonic::Clock represents a steady clock.  Observations of this clock’s time 
    // will only ever increase; never decrease.  The time between ticks of the clock are 
    // constant.
    // The tick period for the clock is 1 microsecond.
    //
    class Clock {
    public:
        static Observation now();
        static Real_time::Observation started_at();
    };

    // Non-member API
    //
    Observation now();

    // A null_time represents an unassigned time observation.
    //
    extern Observation null_time;

    // Helper functions to convert an Observation into 
    // a duration
    //
    Duration microseconds_since(const Observation& obs);
    Duration milliseconds_since(const Observation& obs);
    Duration seconds_since(const Observation& obs);


    // --------------------------------------------------------------------------------
    //
    void sleep_for(const Duration& sleep_period);
    void sleep_until(const Observation& wakeup_time);

    void sleep_for(const Thread_safe::Duration& sleep_period);
    void sleep_until(const Thread_safe::Monotonic::Observation& wakeup_time);


} // namespace Navtech::Time::Monotonic

#endif // MONOTONIC_OBSERVATION_H