// ---------------------------------------------------------------------------------------------------------------------
// Copyright 2025 Navtech Radar Limited
// This file is part of IASDK which is released under The MIT License (MIT).
// See file LICENSE.txt in project root or go to https://opensource.org/licenses/MIT
// for full license details.
//
// Disclaimer:
// Navtech Radar is furnishing this item "as is". Navtech Radar does not provide 
// any warranty of the item whatsoever, whether express, implied, or statutory,
// including, but not limited to, any warranty of merchantability or fitness
// for a particular purpose or any warranty that the contents of the item will
// be error-free.
// In no respect shall Navtech Radar incur any liability for any damages, including,
// but limited to, direct, indirect, special, or consequential damages arising
// out of, resulting from, or any way connected to the use of the item, whether
// or not based upon warranty, contract, tort, or otherwise; whether or not
// injury was sustained by persons or property or otherwise; and whether or not
// loss was sustained from, or arose out of, the results of, the item, or any
// services that may be provided by Navtech Radar.
// ---------------------------------------------------------------------------------------------------------------------
#ifndef REALTIME_OBSERVATION_H
#define REALTIME_OBSERVATION_H

#include <string_view>
#include <string>
#include <iostream>

#include "Time_core.h"

namespace Navtech::Time                         { class Duration; }
namespace Navtech::Time::Monotonic              { class Observation; }
namespace Navtech::Time::Thread_safe            { class Duration; }
namespace Navtech::Time::Thread_safe::Monotonic { class Observation; }

namespace Navtech::Time::Real_time {

    // --------------------------------------------------------------------------------
    // An Observation represents a point in time; more specifically, it represents a 
    // duration since the start of the Clock’s epoch.  An Observation is used to 
    // mark/record an event occurrence.
    // Observations are usually generated by the Clock (via the now() function); but may 
    // be computed from other Observations using Durations as offsets.
    // Real_time::Observation provides an interface for providing day/date/month/etc. 
    // and providing formatted output.
    //
    // Observations support some operator overloads, as follows:
    // - Observations may be compared for equality/inequality.  Equality indicates that 
    //   both Observations mark the same moment in time.
    // - Greater-than indicates that one Observation is later the other; less-than 
    //   indicates that one Observation is earlier than the other.
    // - Adding two Observations has no meaning.
    // - A Duration may be added to, or subtracted from, an Observation.  The result is 
    //   a new Observation.
    // - Since it cannot be guaranteed that two subsequent Observations will yield increasing 
    //   time points, subtracting two Observations may lead to a negative Duration.
    // - To find the absolute difference between two Observations use abs_diff.
    //
    class Observation : public Observation_tag {
    public:
        Observation() = default;
        explicit Observation(const Duration& init);
        explicit Observation(const time_t& init);
        explicit Observation(const timespec& init);

        Duration since_epoch()  const;
        int year()              const;
        int month()             const;
        int day()              const;
        int hour()              const;
        int minute()            const;
        int second()            const;
        int milliseconds()      const;
        int microseconds()      const;

        Observation& format_as(std::string_view fmt);
        std::string to_string() const;

        time_t      to_time_t() const;
        timespec    to_timespec()    const;
        Monotonic::Observation to_monotonic() const;

        Observation& operator+=(const Duration& rhs);
        Observation& operator-=(const Duration& rhs);

    protected:
        std::chrono::time_point<std::chrono::system_clock, std::chrono::microseconds> time { };
        std::string format { "%FT%T.%msZ" };

        Duration get_subseconds() const;
    };

    // Non-member API
    //
    std::ostream& operator<<(std::ostream& os, const Observation& obs);

    Duration abs_diff(const Observation& lhs, const Observation& rhs);


    // --------------------------------------------------------------------------------
    // Real_time::Clock represents the system-wide real time (wall) clock, in UTC(GMT).
    // It may not be monotonic: on most systems, the system time can be adjusted at any 
    // moment. 
    // The epoch of the Clock is unspecified, but most implementations use Unix Time 
    // (that is, time since 00:00:00 Coordinated Universal Time (UTC), Thursday, 1 January 1970).
    // The tick period for the clock is 1 microsecond.
    //
    class Clock {
    public:
        static Observation now();
    };

    // Non-member API
    //
    Observation now(); 

    // A null_time represents an unassigned time observation.
    //
    extern Observation null_time;

    // Helper functions to convert an Observation into 
    // a duration
    //
    Duration microseconds_since(const Observation& obs);
    Duration milliseconds_since(const Observation& obs);
    Duration seconds_since(const Observation& obs);


} // namespace Navtech::Time::Real_time

#endif // REALTIME_OBSERVATION_H