# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: configurationdata.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nvramcontents_pb2 as nvramcontents__pb2
import softwareversions_pb2 as softwareversions__pb2
import radarmodel_pb2 as radarmodel__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63onfigurationdata.proto\x12#Navtech.Core.Configuration.Protobuf\x1a\x13nvramcontents.proto\x1a\x16softwareversions.proto\x1a\x10radarmodel.proto\"\x98\x04\n\x11\x43onfigurationData\x12>\n\x05model\x18\x01 \x01(\x0b\x32/.Navtech.Core.Configuration.Protobuf.RadarModel\x12\x12\n\nmacaddress\x18\x02 \x01(\t\x12O\n\x10softwareversions\x18\x03 \x01(\x0b\x32\x35.Navtech.Core.Configuration.Protobuf.SoftwareVersions\x12I\n\rnvramcontents\x18\x04 \x01(\x0b\x32\x32.Navtech.Core.Configuration.Protobuf.NVRamContents\x12\x19\n\x11rangeresolutionhz\x18\x05 \x01(\x02\x12\x1a\n\x12moduleserialnumber\x18\x06 \x01(\t\x12\x15\n\rautotunevalue\x18\x07 \x01(\x05\x12\x15\n\rradaruniqueid\x18\x08 \x01(\t\x12\x11\n\tdatawidth\x18\t \x01(\x05\x12\x1d\n\x15rangeresolutionmetres\x18\n \x01(\x02\x12L\n\rradarfeatures\x18\x0b \x01(\x0e\x32\x35.Navtech.Core.Configuration.Protobuf.RadarFeatureFlag\x12\x13\n\x0bstaringmode\x18\x0c \x01(\x05\x12\x19\n\x11onboardmacaddress\x18\r \x01(\t')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'configurationdata_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONFIGURATIONDATA._serialized_start=128
  _CONFIGURATIONDATA._serialized_end=664
# @@protoc_insertion_point(module_scope)
