# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: discovery.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import radarmodel_pb2 as radarmodel__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64iscovery.proto\x12#Navtech.Core.Configuration.Protobuf\x1a\x10radarmodel.proto\"\x99\x02\n\tDiscovery\x12>\n\x05model\x18\x01 \x01(\x0b\x32/.Navtech.Core.Configuration.Protobuf.RadarModel\x12\x19\n\x11maxclientsallowed\x18\x02 \x01(\x05\x12\x11\n\tipclients\x18\x03 \x03(\t\x12\x15\n\rradarfeatures\x18\x04 \x01(\r\x12\x13\n\x0bstaringmode\x18\x05 \x01(\x05\x12\x1a\n\x12transmitterenabled\x18\x06 \x01(\x05\x12\x1d\n\x15rangeresolutionmetres\x18\x07 \x01(\x02\x12\x19\n\x11onboardmacaddress\x18\x08 \x01(\t\x12\x1c\n\x14\x65xtendedfeatureflags\x18\t \x01(\x08')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'discovery_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DISCOVERY._serialized_start=75
  _DISCOVERY._serialized_end=356
# @@protoc_insertion_point(module_scope)
