# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: healthinfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10healthinfo.proto\x12#Navtech.Core.Configuration.Protobuf\"\xfb\x01\n\nHealthInfo\x12\x15\n\x08minvalue\x18\x01 \x01(\x02:\x03-10\x12\x14\n\x08maxvalue\x18\x02 \x01(\x02:\x02\x31\x30\x12\x10\n\x05value\x18\x03 \x01(\x02:\x01\x30\x12\x10\n\x05\x64\x65lta\x18\x04 \x01(\x02:\x01\x30\x12J\n\x06status\x18\x05 \x01(\x0e\x32\x31.Navtech.Core.Configuration.Protobuf.HealthStatus:\x07UNKNOWN\x12\x19\n\rwarnallowance\x18\x06 \x01(\x05:\x02\x31\x32\x12\x1a\n\x0e\x61larmallowance\x18\x07 \x01(\x05:\x02\x32\x30\x12\x19\n\x0e\x63learallowance\x18\x08 \x01(\x05:\x01\x31*D\n\x0cHealthStatus\x12\r\n\tUNHEALTHY\x10\x00\x12\x0b\n\x07WARNING\x10\x01\x12\x0b\n\x07HEALTHY\x10\x02\x12\x0b\n\x07UNKNOWN\x10\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'healthinfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HEALTHSTATUS._serialized_start=311
  _HEALTHSTATUS._serialized_end=379
  _HEALTHINFO._serialized_start=58
  _HEALTHINFO._serialized_end=309
# @@protoc_insertion_point(module_scope)
