# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: networkinfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11networkinfo.proto\x12#Navtech.Core.Configuration.Protobuf\"\xa2\x01\n\x0bNetworkInfo\x12@\n\x05state\x18\x01 \x01(\x0e\x32\x31.Navtech.Core.Configuration.Protobuf.NetworkState\x12\x42\n\x06\x64uplex\x18\x02 \x01(\x0e\x32\x32.Navtech.Core.Configuration.Protobuf.NetworkDuplex\x12\r\n\x05speed\x18\x03 \x01(\r*B\n\x0cNetworkState\x12\x0c\n\x08NET_DOWN\x10\x00\x12\n\n\x06NET_UP\x10\x01\x12\x18\n\x0bNET_UNKNOWN\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01*+\n\rNetworkDuplex\x12\x0c\n\x08NET_HALF\x10\x00\x12\x0c\n\x08NET_FULL\x10\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'networkinfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NETWORKSTATE._serialized_start=223
  _NETWORKSTATE._serialized_end=289
  _NETWORKDUPLEX._serialized_start=291
  _NETWORKDUPLEX._serialized_end=334
  _NETWORKINFO._serialized_start=59
  _NETWORKINFO._serialized_end=221
# @@protoc_insertion_point(module_scope)
