# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nvramcontents.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13nvramcontents.proto\x12#Navtech.Core.Configuration.Protobuf\"\xa3\x03\n\rNVRamContents\x12\r\n\x05radar\x18\x01 \x01(\x05\x12\x14\n\x0c\x64igitalboard\x18\x02 \x01(\x05\x12\x10\n\x08\x66rontend\x18\x03 \x01(\x05\x12\x15\n\rdaughterboard\x18\x04 \x01(\x05\x12@\n\x08lenstype\x18\x05 \x01(\x0e\x32..Navtech.Core.Configuration.Protobuf.LensTypes\x12J\n\x0borientation\x18\x06 \x01(\x0e\x32\x35.Navtech.Core.Configuration.Protobuf.OrientationTypes\x12\x11\n\tpoefitted\x18\x07 \x01(\x05\x12\x14\n\x0cheaterfitted\x18\x08 \x01(\x05\x12\x11\n\tbossangle\x18\t \x01(\x02\x12\x11\n\tprofileid\x18\n \x01(\x05\x12\x11\n\tbuilddate\x18\x0b \x01(\x05\x12\x13\n\x0bservicedate\x18\x0c \x01(\x05\x12\x0f\n\x07modelid\x18\r \x01(\t\x12\x0e\n\x06\x61\x63\x63\x65lx\x18\x0e \x01(\x05\x12\x0e\n\x06\x61\x63\x63\x65ly\x18\x0f \x01(\x05\x12\x0e\n\x06\x61\x63\x63\x65lz\x18\x10 \x01(\x05*C\n\tLensTypes\x12\x08\n\x04\x46LAT\x10\x00\x12\x0c\n\x08\x43OSECANT\x10\x01\x12\x0c\n\x08\x44ISHFLAT\x10\x02\x12\x10\n\x0c\x44ISHCOSECANT\x10\x03*+\n\x10OrientationTypes\x12\n\n\x06NORMAL\x10\x00\x12\x0b\n\x07HANGING\x10\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nvramcontents_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LENSTYPES._serialized_start=482
  _LENSTYPES._serialized_end=549
  _ORIENTATIONTYPES._serialized_start=551
  _ORIENTATIONTYPES._serialized_end=594
  _NVRAMCONTENTS._serialized_start=61
  _NVRAMCONTENTS._serialized_end=480
# @@protoc_insertion_point(module_scope)
