# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: radarmodel.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10radarmodel.proto\x12#Navtech.Core.Configuration.Protobuf\"b\n\nRadarModel\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08uniqueid\x18\x03 \x01(\t\x12\x15\n\rrangeinmetres\x18\x04 \x01(\x02\x12\x11\n\tprofileid\x18\x05 \x01(\t*f\n\x10RadarFeatureFlag\x12\x08\n\x04NONE\x10\x00\x12\x0c\n\x08\x41UTOTUNE\x10\x01\x12$\n SECONDARYPROCESSUNGMODULEPRESENT\x10\x02\x12\x14\n\x10NONCONTOUREDDATA\x10\x04')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'radarmodel_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RADARFEATUREFLAG._serialized_start=157
  _RADARFEATUREFLAG._serialized_end=259
  _RADARMODEL._serialized_start=57
  _RADARMODEL._serialized_end=155
# @@protoc_insertion_point(module_scope)
