# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: softwareversions.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16softwareversions.proto\x12#Navtech.Core.Configuration.Protobuf\"\xb0\x01\n\x10SoftwareVersions\x12\n\n\x02os\x18\x01 \x01(\t\x12\x10\n\x08\x66irmware\x18\x02 \x01(\t\x12\n\n\x02ui\x18\x03 \x01(\t\x12\x11\n\tonboardos\x18\x04 \x01(\t\x12\x17\n\x0fonboardfirmware\x18\x05 \x01(\t\x12\x11\n\tradarfpga\x18\x06 \x01(\t\x12\x19\n\x11\x61nalogueboardfpga\x18\x07 \x01(\t\x12\x18\n\x10\x64igitalboardfpga\x18\x08 \x01(\t')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'softwareversions_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SOFTWAREVERSIONS._serialized_start=64
  _SOFTWAREVERSIONS._serialized_end=240
# @@protoc_insertion_point(module_scope)
