# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: timestatus.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10timestatus.proto\x12#Navtech.Core.Configuration.Protobuf\"\xde\x01\n\nTimeStatus\x12\x12\n\nptpenabled\x18\x01 \x01(\x08\x12\x12\n\nntpenabled\x18\x02 \x01(\x08\x12@\n\x07ptpsync\x18\x03 \x01(\x0e\x32/.Navtech.Core.Configuration.Protobuf.SyncStatus\x12@\n\x07ntpsync\x18\x04 \x01(\x0e\x32/.Navtech.Core.Configuration.Protobuf.SyncStatus\x12\x11\n\tptpremote\x18\x05 \x01(\t\x12\x11\n\tntpremote\x18\x06 \x01(\t*D\n\nSyncStatus\x12\x10\n\x0cSYNC_UNKNOWN\x10\x00\x12\x12\n\x0eUNSYNCHRONISED\x10\x01\x12\x10\n\x0cSYNCHRONISED\x10\x02')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'timestatus_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SYNCSTATUS._serialized_start=282
  _SYNCSTATUS._serialized_end=350
  _TIMESTATUS._serialized_start=58
  _TIMESTATUS._serialized_end=280
# @@protoc_insertion_point(module_scope)
