# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tls.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ttls.proto\x12\x03TLS\"]\n\x0cTLS_settings\x12\x1a\n\x12server_certificate\x18\x01 \x01(\t\x12\x12\n\nserver_key\x18\x02 \x01(\t\x12\x1d\n\x15server_key_passphrase\x18\x03 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tls_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TLS_SETTINGS._serialized_start=18
  _TLS_SETTINGS._serialized_end=111
# @@protoc_insertion_point(module_scope)
